# Generated by Django 3.0.7 on 2020-06-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_proj',
            field=models.IntegerField(choices=[(0, 'c'), (1, 'c++'), (2, 'flutter'), (3, 'web')], default=0),
        ),
    ]
