# Generated by Django 3.0.7 on 2020-06-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_type_proj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_proj',
            field=models.IntegerField(choices=[('C', 'c'), ('C++', 'c++'), ('FLUTTER', 'flutter'), ('WEB', 'web')], default=0),
        ),
    ]
