# Generated by Django 3.0.7 on 2020-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200617_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_proj',
            field=models.IntegerField(choices=[('C', 'c'), ('C++', 'c++'), ('FLUTTER', 'flutter'), ('WEB', 'web')], default='C'),
        ),
    ]
