# Generated by Django 3.0.7 on 2020-06-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200617_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_proj',
            field=models.CharField(choices=[('0', 'c'), ('1', 'c++'), ('2', 'flutter'), ('3', 'web')], default='C', max_length=1),
        ),
    ]
